[project]
name = "tag-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "distrax>=0.1.7",
    "evosax>=0.2.0",
    "fastapi>=0.116.1",
    "flax>=0.12.4",
    "imageio>=2.37.2",
    "imageio-ffmpeg>=0.6.0",
    "mujoco>=3.4.0",
    "mujoco-mjx>=3.4.0",
    "optax>=0.2.6",
    "tensorboardX>=2.6",
    "tqdm>=4.67.3",
    "opencv-python>=4.13.0.92",
    "pupil-apriltags>=1.0.4.post11",
    "jax>=0.9.1",
    "uvicorn[standard]>=0.35.0",
    "numpy>=2.4.3",
]

[project.optional-dependencies]
cuda = [
    "jax[cuda12]>=0.9.0.1",
]
cuda13 = [
    "jax[cuda13]>=0.9.0.1",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pybind11-stubgen>=2.5.5",
    "pyright>=1.1.408",
    "ruff>=0.15.2",
]

[tool.pyright]
stubPath = ".typings/"

[tool.tag_rl]
jax_cache_dir = ".cache/jax"
